### ISSUE TITLE
Visualization Tool

### ISSUE THREAD

**Issue by nbansal90** [IceTTTb/NopeSAC#3]
Hey @cherubicXN, @IceTTTb 

I am looking to qualitatively verify a model trained on the back of your work. For me the `training/evaluation/inference ` pipeline is working fine after relevant changes in the Data and Model, but was encountering some major issues  while trying to visualize the intermediate/final results.
Request you to share the necessary files for visualization. An initial (working) version of the files would also be suffice to get me started and change according to my needs.

Thank you.
Nitin

**Comment by IceTTTb** [comment]
Hey @nbansal90 

The visualization code is now available. You can run `python vis_NopeSAC.py` to get the reconstructed results.

**Comment by nbansal90** [comment]
Thanks @IceTTTb ! Will close this for now.
